### PR TITLE
Fix mx dns lookup

### PR DESCRIPTION
**Pull request by lauraeci**
Fixes failure in MX DNS lookup when one MX record fails to get an IP address.

### CODE REVIEW

**Comment by afair** [comment]
Thanks! I have updates in the v0.1.2 branch that fixes the travis errors, so don't worry about that.

Also, inserting an empty array on DNS Error may cause problems using that data. Perhaps we should no create an item. (return nil instead of [] and to a .compact on the resulting array?)

**Comment by lauraeci** [comment]
Thank you, @afair.  Sounds good to me.  Updated with that change. :)

**Comment by lauraeci** [comment]
Hi @afair,

Should I leave this PR on master or move it to v0.1.2, just wondering when you plan to do your next release.

Cheers,
-Laura

**Comment by afair** [comment]
Thanks, @lauraeci, I'll handle it. I have other work as well.

**Pull request merged**
