### PR TITLE
Add turkish locales

### PR DESCRIPTION
**Pull request by msdundar**
References afair/email_address#24 and omu/nokul#147

### CODE REVIEW

**Comment by msdundar** [comment]
@afair WDYT?

**Comment by AlexWayfer** [comment]
> msdundar closed this 23 minutes ago

Why? 😥

**Comment by msdundar** [comment]
@AlexWayfer No feedback to this PR since 1,5 years.

**Comment by AlexWayfer** [comment]
> @AlexWayfer No feedback to this PR since 1,5 years.

OK. It may will come after 1.5 years more. But… I still see no reason to close PR. It can be open also for gem maintenance level review (count of open issues, open PRs, etc.)

**Comment by roktas** [comment]
> It may will come after 1.5 years more. 

Huh...  1.5 years plus 1.5 years more...  @AlexWayfer Do you really think this is normal (no code, just a few YAML lines you can add by just clicking a button)?  Anyway, thanks for your efforts; just couldn't resist to reply your comment.

**Comment by AlexWayfer** [comment]
> Huh... 1.5 years plus 1.5 years more... @AlexWayfer Do you really think this is normal (no code, just a few YAML lines you can add by just clicking a button)?

Yes, I think a lack of responsibility is OK for free open source project.

**Pull request closed without merging**
